### PR TITLE
Fetch Lab Data Mart KSSL data with `fetchLDM`

### PR DESCRIPTION
**Pull request by brownag**
"new" tools for querying lab data from SDA Lab Data Mart. 

# Query data from Kellogg Soil Survey Laboratory Data Mart via Soil Data Access
 
## LDM model diagram: 
 - https://jneme910.github.io/Lab_Data_Mart_Documentation/Documents/SDA_KSSL_Data_model.html

## `fetchLDM()`
- param `x` a vector of values to find in column specified by `what`
- param `dsn` data source name; either a path to a SQLite database, an open DBIConnection or (default) `NULL` (to use `soilDB::SDA_query`)
- param `what` a single column name from tables: `lab_combine_nasis_ncss`, `lab_webmap`, `lab_site`, `lab_pedon` or `lab_area`
- param `bycol` a single column name from `lab_layer` used for processing chunks; default: `"pedon_key"`
- param `tables` a vector of table names; one or more of: `"lab_physical_properties"`, `"lab_mineralogy_glass_count"`, `"lab_chemical_properties"`, `"lab_major_and_trace_elements_and_oxides"`, `"lab_xray_and_thermal"`, `"lab_calculations_including_estimates_and_default_values"`, `"lab_rosetta_Key"`
- param `chunk.size` number of pedons per chunk (for queries that may exceed `maxJsonLength`)
- param `ntries` number of tries (times to halve `chunk.size`) before returning `NULL`; default `3`
- param `prep_code` Default: `"S"`. One or more of `"GP"`, `"M"`, `"N"`, or `"S"`
- param `analyzed_size_frac` Default: `"<2 mm"`. One or more of `"<2 mm"`, `"0.02-0.05 mm"`, `"0.05-0.1 mm"`, `"1-2 mm"`, `"0.5-1 mm"`, `"0.25-0.5 mm"`, `"0.05-2 mm"`, `"0.02-2 mm"`, `"0.1-0.25 mm"`, `"<0.002 mm`
- details If the `chunk.size` parameter is set too large and the Soil Data Access request fails, the algorithm will re-try the query with a smaller (halved) `chunk.size` argument. This will be attempted up to 3 times before returning `NULL` Currently the `lab_area` tables are joined only for the "Soil Survey Area" related records.
- return a `SoilProfileCollection` for a successful query, a `try-error` if no site/pedon locations can be found or `NULL` for an empty `lab_layer` (within sites/pedons) result

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Probably about time to retire `fetchKSSL` anyway.

**Comment by dylanbeaudette** [comment]
Did some stress testing this morning. I like how well this scales to larger queries. 

I've got a suggestion, which can be implemented as an additional argument: allow for the selection of suites of columns. We can leave the default as the kitchen sink, but it would be nice to specify (at least) most common (physical + chemical), calculations, geochemical--or some mixture of those. I'll think about some simple ways of encoding these selections. This would offset some of the processing time + serialization overhead when much of the geochemical data are known to be missing and left out on purpose.

I'll check-in with Jason on planned updates to these tables. Last I checked there were a couple important TODOs:
* fix truncated field names
* include `labsampnum` in the 'rosetta' table
* update NASIS--LDM integration report
* remove duplicated columns shared among some of the pedon/site level tables

**Comment by brownag** [comment]
Thanks for your suggestions. I have plans to implement that (selection of columns)

**Comment by brownag** [comment]
fetchLDM can now take a `dsn` argument -- either _character_ or _DBIConnection_ for local instances of SQLite database or anything else with same schema you can connect to with DBI.
 Default `dsn = NULL` uses SDA_query and the snapshot of the LDM available via Soil Data Access API.

**Comment by brownag** [comment]
Need to plan how to deal with many:1 relationships for glass/geochemical/x-ray/thermal/calculations data (e.g. measured under different `prep_code` and/or `analyzed_size_frac`) for a given layer/`labsampnum`. Currently these do not cause an error but the details of the fractionation can be obscured and duplication of some layers may occur in the resuting SPC

**Comment by dylanbeaudette** [comment]
> fetchLDM can now take a `dsn` argument -- either _character_ or _DBIConnection_ for local instances of SQLite database or anything else with same schema you can connect to with DBI.
> 
> Default `dsn = NULL` uses SDA_query and the snapshot of the LDM available via Soil Data Access API.
> 
> Using the local instance is quite a bit faster and does not require "chunking"
> 
> ```r
> library(soilDB)
> system.time(mollisols <- fetchLDM("mollisols", dsn = "E:/Geodata/soils/LDM-compact.sqlite", what = "corr_taxorder"))
> #> Warning: Horizon top depths contain NA! Check depth logic with
> #> aqp::checkHzDepthLogic()
> #> Warning: Horizon bottom depths contain NA! Check depth logic with
> #> aqp::checkHzDepthLogic()
> #>    user  system elapsed 
> #>   17.92    1.78   19.92
> ```

Nice. I'll double-check, but the LDM-compact.sqlite DB should have some basic indexing on the table keys. There is no reason we cannot add some additional indexes on commonly used columns to further improve this kind of query.

**Comment by dylanbeaudette** [comment]
> Need to plan how to deal with many:1 relationships for glass/geochemical/x-ray/thermal/calculations data (e.g. measured under different `prep_code` and/or `analyzed_size_frac`) for a given layer/`labsampnum`. Currently these do not cause an error but the details of the fractionation can be obscured and duplication of some layers may occur in the resuting SPC

True. This is a more generic problem that is partially dealt with at LDM snapshot creation, but ultimately something that needs to change in the underlying table structure. If you have a couple of examples handy, I'll pass on to Jason. I very much doubt that those tables were included in the simplification that was applied to physical and chemical data.

**Comment by brownag** [comment]
> > Need to plan how to deal with many:1 relationships for glass/geochemical/x-ray/thermal/calculations data (e.g. measured under different `prep_code` and/or `analyzed_size_frac`) for a given layer/`labsampnum`. Currently these do not cause an error but the details of the fractionation can be obscured and duplication of some layers may occur in the resuting SPC
> 
> True. This is a more generic problem that is partially dealt with at LDM snapshot creation, but ultimately something that needs to change in the underlying table structure.

I was thinking along the lines of an argument that allows selection of common size fractions, most complete data (keeping track of fraction selected), etc.

 If one needs more complete fractionation information (say, for example aggregating [glass counts](https://github.com/brownag/sANDREWbox/blob/master/KSSLExtended/fetchKSSL_glasscount_demo.R)) then writing a custom query/using the whole `lab_mineralogy_glass_count` table as starting point is probably the right approach rather than `fetchLDM`. In general for these many:1 cases in the lab data there are assumptions that need to be made given that we don't usually exhaustively measure things on all possible fractions for all horizons.

For fetchLDM there just needs to be easy ways for the analyst to pick what they are interested in. Some heuristics to decide which records could be joined for a reasonably complete result are possible. i.e. only merge records where the size fraction is `X` or prep code is in `Y`, or take a single "most complete" record, recording the information about the selection in a new column.

> If you have a couple of examples handy, I'll pass on to Jason. 

OK.. here is a example, swap in your favorite taxon for many more instances. In the Xerolls I get 1146 profiles correlated. If I join in the tables other than physical/chemical, 135 profiles wind up with "duplicated" horizons vis a vis `checkHzDepthLogic` (due to the many:1 join w/ `labsampnum` as the unique horizon identifier.)

``` r
library(aqp, warn=FALSE)
#> This is aqp 1.30
library(soilDB)

spc_simple <- fetchLDM(
  "XEROLLS",
  dsn = "E:/Geodata/soils/LDM-compact.sqlite",
  what = "corr_taxsuborder",
  tables = c("lab_physical_properties",
             "lab_chemical_properties")
)
#> Warning: Horizon top depths contain NA! Check depth logic with
#> aqp::checkHzDepthLogic()
#> Warning: Horizon bottom depths contain NA! Check depth logic with
#> aqp::checkHzDepthLogic()

spc_all <- fetchLDM("XEROLLS",
                    dsn = "E:/Geodata/soils/LDM-compact.sqlite",
                    what = "corr_taxsuborder")
#> Warning: Horizon top depths contain NA! Check depth logic with
#> aqp::checkHzDepthLogic()

#> Warning: Horizon bottom depths contain NA! Check depth logic with
#> aqp::checkHzDepthLogic()

simple_depth_logic <- checkHzDepthLogic(spc_simple)
all_depth_logic <- checkHzDepthLogic(spc_all)
spc_all$valid <- all_depth_logic$valid

check_these <- subset(spc_all,!valid & pedon_key %in% simple_depth_logic[simple_depth_logic$valid, 'pedon_key'])

# approx 15% of 1146 xerolls have one or more horizons where there is a many:1 relationship to labsampnum
prop.table(table(spc_all$pedon_key %in% check_these$pedon_key))
#> 
#>    FALSE     TRUE 
#> 0.843006 0.156994

# plot(check_these[1:3, ])
# View(horizons(check_these[1:3, ]))

countcheck <- table(check_these$labsampnum)

# what labsampnum are "duplicated"?
dput(names(countcheck[countcheck > 1]))
#> c("01N00842", "01N00844", "01N00851", "01N00853", "01N00855", 
#> "01N00857", "01N00858", "01N00860", "01N00863", "01N00866", "01N00868", 
#> "01N00870", "01N01558", "01N01561", "01N02133", "01N02134", "01N02907", 
#> "01N02908", "01N02909", "02N00256", "02N00257", "02N00258", "02N00289", 
#> "02N00290", "02N00291", "02N00298", "02N00300", "02N00301", "02N03137", 
#> "02N03162", "02N04519", "02N05677", "02N05679", "02N05695", "03N01494", 
#> "03N01496", "03N01497", "03N01498", "03N01499", "03N01500", "03N01760", 
#> "03N01761", "03N01763", "03N01764", "03N01765", "03N01766", "03N01768", 
#> "03N01769", "03N01770", "03N01771", "03N01854", "03N01855", "03N01856", 
#> "03N01857", "03N01858", "03N01859", "03N01860", "03N01861", "03N01863", 
#> "03N01864", "03N01865", "03N04460", "03N04461", "03N04462", "03N04465", 
#> "03N04467", "03N04468", "03N04471", "03N04686", "03N04687", "03N04688", 
#> "03N04689", "03N04690", "03N04691", "03N04705", "03N04706", "03N04707", 
#> "03N04708", "03N04709", "03N04710", "03N04725", "03N04727", "03N04728", 
#> "03N04729", "03N04730", "03N04731", "03N04732", "03N04733", "03N04734", 
#> "03N04735", "03N04736", "03N04737", "03N04738", "03N04739", "03N04740", 
#> "04N00427", "04N00428", "04N00429", "04N00435", "04N00436", "04N00437", 
#> "04N00438", "04N00439", "04N00440", "04N00442", "04N00443", "04N00770", 
#> "04N01924", "04N01925", "04N02088", "04N02089", "04N02091", "04N02092", 
#> "04N02367", "04N02368", "04N02369", "04N02411", "04N02412", "04N02413", 
#> "04N02415", "04N05478", "04N05479", "04N05480", "04N05481", "04N05482", 
#> "04N05483", "04N05484", "04N06193", "04N06195", "04N06196", "04N06197", 
#> "04N06198", "04N06199", "04N06200", "04N06202", "04N06204", "04N06207", 
#> "04N06208", "04N06209", "04N06210", "04N06211", "04N06212", "04N06213", 
#> "04N06214", "04N06215", "04N06216", "04N06217", "04N06218", "04N06219", 
#> "04N06220", "04N06221", "04N06222", "04N06223", "04N06224", "05N00479", 
#> "05N00480", "05N00482", "05N00485", "05N00487", "05N00494", "05N00712", 
#> "05N00713", "05N00730", "05N00732", "05N00733", "05N00735", "05N00736", 
#> "05N00737", "05N00739", "05N02186", "05N02188", "05N02190", "05N02192", 
#> "05N02194", "05N03218", "05N03221", "05N03224", "05N03225", "05N03229", 
#> "05N03231", "05N03600", "05N03601", "05N03607", "05N03608", "05N03609", 
#> "06N00717", "06N00719", "06N00740", "06N00741", "06N00744", "06N00746", 
#> "06N00748", "06N00751", "06N00926", "06N00928", "06N00930", "06N00935", 
#> "06N00937", "06N00939", "06N00941", "06N00953", "06N00955", "06N00957", 
#> "06N00961", "06N00963", "06N00965", "06N00966", "06N00967", "06N00969", 
#> "06N03273", "06N03275", "07N00959", "07N00960", "07N00961", "07N00962", 
#> "07N00963", "07N00964", "07N04110", "07N04111", "07N04115", "07N04117", 
#> "07N04122", "07N04124", "07N04131", "07N04136", "07N04137", "07N04143", 
#> "07N04144", "08N01260", "08N02937", "08N02938", "08N02939", "08N02940", 
#> "08N02941", "08N02942", "08N02944", "08N02945", "08N02946", "08N02947", 
#> "08N02948", "09N00795", "09N00796", "09N00797", "09N01588", "09N01589", 
#> "09N01593", "09N01598", "09N02674", "09N04557", "09N04558", "09N04560", 
#> "09N04561", "09N04562", "09N04565", "09N04566", "09N04567", "09N04570", 
#> "10N01439", "10N01704", "10N01706", "10N01707", "10N01708", "10N01711", 
#> "10N01713", "10N01714", "10N01718", "10N01721", "10N01722", "10N02311", 
#> "10N02313", "11N00406", "11N00413", "11N00419", "11N00438", "11N04037", 
#> "11N04038", "12N01161", "12N01162", "12N01163", "13N05934", "13N05935", 
#> "14N03421", "14N03422", "14N03423", "14N03424", "15N02504", "15N02505", 
#> "15N02506", "15N02507", "15N02508", "15N02509", "15N02510", "15N02511", 
#> "16N01107", "16N01108", "16N01109", "16N01110", "16N01111", "16N01112", 
#> "16N01113", "16N01114", "16N01115", "16N01116", "16N01117", "16N01118", 
#> "16N01119", "16N01122", "16N01123", "16N01124", "16N01125", "16N01126", 
#> "16N01127", "17N03140", "17N03141", "17N03142", "17N03143", "17N03146", 
#> "17N03147", "17N03148", "17N03149", "17N03152", "17N03153", "17N03154", 
#> "17N03155", "17N03156", "17N03166", "17N03167", "17N03168", "40A25351", 
#> "78P02393", "78P02553", "78P02554", "78P02555", "78P03096", "78P03097", 
#> "78P03098", "78P03099", "78P03100", "79P01180", "79P02288", "79P02293", 
#> "79P02300", "79P02303", "79P02307", "79P02312", "80P02545", "80P02546", 
#> "80P02547", "80P02549", "81P04204", "81P04205", "81P04528", "82P00778", 
#> "82P00779", "88P03641", "88P03644", "90P06183", "90P06185", "90P06187", 
#> "90P06189", "90P06190", "90P06191", "90P06192", "90P06193", "90P06194", 
#> "90P06195", "90P06196", "90P06197", "90P06198", "90P06199", "90P06200", 
#> "90P06201", "90P06202", "90P06209", "90P06210", "90P06211", "90P06221", 
#> "90P06222", "90P06223", "90P06224", "90P06225", "90P06226", "90P06227", 
#> "90P06240", "90P06242", "90P06244", "90P06246", "90P06248", "90P06250", 
#> "90P06252", "90P06254", "90P06256", "92P00532", "92P00541", "92P00542", 
#> "92P00543", "95P00412", "95P00413", "95P00414", "99P00279", "99P00280", 
#> "99P00281", "99P00828", "99P00833", "99P00848", "99P00854", "99P00860"
#> )

# currently fetchLDM makes no effort to filter horizon data based on prep code, size frac
unique(horizons(check_these)$prep_code)
#> [1] "N"  "S"  NA   "GP"
unique(horizons(check_these)$analyzed_size_frac)
#> [1] "0.1-0.25 mm"  "0.02-0.05 mm" "0.05-0.1 mm"  NA             "0.25-0.5 mm" 
#> [6] "<2 mm"
```

> I very much doubt that those tables were included in the simplification that was applied to physical and chemical data.

I think it makes sense they were not included--it would be a combinatorial explosion. 

I can imagine "making more columns" in a _very_ wide format spanning all possible fractions/prep codes as the "brute force" approach... though the naming of columns would become even more difficult. And it would mostly be empty (already the case). And in practice it would probably only confuse/detract from the more common analyses -- where for instance you would only want say <2mm data to be compared with other <2mm data.

**Comment by brownag** [comment]
https://github.com/ncss-tech/soilDB/pull/182/commits/147fbc2ae36edeac7ff5ff9e07ac74df0bcf6b0a implements two new arguments for filtering the _lab_layer_ result based on `prep_code` and `analyzed_size_frac`. Default size fraction uses `"S"` sieved and  `<2 mm` for size fraction

**Comment by brownag** [comment]
This reprex shows latest (refactored) behavior. Now there is a separate query made if user requests the Xray/thermal/mineralogy/glass data that are fractionated... and those data are cleanly joined back to a (usually more complete) set of records based on tables that are 1:1 with _lab_layer_. 

A value of `NA` in `analyzed_size_frac` is currently an indicator of `labsampnum` records that do not have fractionated data;

``` r
library(soilDB)

res <- fetchLDM("Typic Argialbolls",
                 what = "corr_taxsubgrp",
                 tables = c("lab_physical_properties",
                            "lab_chemical_properties"))
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> converting profile IDs from integer to character
# 35 profiles
length(res)
#> [1] 35

res2 <- fetchLDM("Typic Argialbolls",
                 what = "corr_taxsubgrp",
                 tables = c("lab_physical_properties",
                            "lab_chemical_properties",
                            "lab_xray_and_thermal"))
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> no fractionated samples found for selected prep_code (S) and analyzed_size_frac (<2 mm)
#> converting profile IDs from integer to character

# no X-ray/thermal data for default analyzed_size_frac="<2mm
all(is.na(res2$analyzed_size_frac))
#> [1] TRUE

# if we specify a size fraction, we get just the horizons that have XRD data in that fraction
res3 <- fetchLDM("Typic Argialbolls",
                 what = "corr_taxsubgrp",
                 tables = c("lab_physical_properties",
                            "lab_chemical_properties",
                            "lab_xray_and_thermal"),
                 analyzed_size_frac = c("<0.002 mm"))
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> single result set, returning a data.frame
#> converting profile IDs from integer to character
inherits(res3, 'SoilProfileCollection')
#> [1] TRUE

table(res3$analyzed_size_frac)
#> 
#> <0.002 mm 
#>        50

# logic is mostly valid after filling gaps
res3fill <- aqp::fillHzGaps(res3)

res3fill$hazQZ <- !is.na(res3fill$QZ_Quartz_X_Ray)

# the standard <2mm chemical physical analyses (e.g. PSDA / clay_total) INNER JOINed to fractionated data
aqp::plot(res3fill, color = "hazQZ")
```

**Comment by brownag** [comment]
https://github.com/ncss-tech/soilDB/blob/989cf9e685b0e62e5388ea823d7aa044f3c0c787/R/SDA_query.R#L168-L183

Playing around with suggestions from @jneme910 on another branch; goal to be a bit more intelligent about how we approach queries that exceed the JS maxJsonLength of 32Mb. I have started to generalize my multi-query approach back to a single-query approach... which seems to works for small payload, but seems to exceed the 300MB memory threshold with some of the larger queries. Therefore this branch that is tracked in this PR is still using the my "stubborn" approach that errors out the first time, then proceeds to chunk up and query subsets of 1000 pedon_key until the result is obtained. 

Won't be merging this PR this week.

**Pull request merged**
