### PR TITLE
`simplifyColorData`, `estimateColorMixture`: use data.table

### PR DESCRIPTION
**Pull request by brownag**
Should make these routines a bit faster. Needs a little more before/after testing, but never pushed this branch to origin.

### CODE REVIEW

**Comment by dylanbeaudette** [comment]
Cool. I bet similar code in aqp could use a similar upgrade. Note that I'd like to eventually (soon) replace `soilDB::estimateColorMixture()` with `aqp::mixMunsell(..., method = 'estimate')`. We can do this outside of this PR.

**Comment by brownag** [comment]
In terms of speed a modest (~5 s) improvement with ~4700 pedons mixing about 500 horizons each of moist and dry. Note that this is a "typical" case -- but the data.table optimizations likely offer much more significant benefits when the SPC is large (>10k profiles). Following on from earlier plyr -> base optimization here https://github.com/ncss-tech/soilDB/issues/55

> mixing dry colors ... [422 of 20278 horizons]
> mixing moist colors ... [547 of 23362 horizons]

## Before (current master branch)
image

About 16 seconds (half the execution time) goes to `rgb2munsell` / `farver::compare_colour`.

## After (this PR)

image

Similar breakdown... maybe a little bit faster iteration, but the core code being executed (now by data.table) is unchanged and `rgb2munsell` is still the main workhorse for color code.

---

There are fairly significant differences between the `mixMunsell` and `estimateColorMixture` -- such that the former will not be a drop in replacement within `simplifyColorData` (and all of the table columns that go into fetchNASIS result) without refactoring or writing a wrapper method.

**Comment by brownag** [comment]
Confirmed parity before/after for sRGB hex values in fetchNASIS result, so I will merge this and we can replace the color mixing code with aqp equivalents some time in the future

**Comment by dylanbeaudette** [comment]
Awesome, thanks for all of the benchmarking / testing.

**Pull request merged**
